- hosts: localhost
  tasks:
  - name: install git
    yum: name=git state=latest
    become: yes
    become_method: sudo
  - name: clone my devops repoe
    git: clone=yes repo=https://github.com/amitene/devops.git dest=/home/ec2-user/devops/
  - name: clone the spring repo
    git: clone=yes repo=https://github.com/amitene/spring-petclinic.git dest=/home/ec2-user/spring-petclinic/
